/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.3 at Sun May 31 01:25:59 2015. */

#include "communication.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t CompressorSettings_fields[14] = {
    PB_FIELD(  1, INT32   , OPTIONAL, STATIC  , FIRST, CompressorSettings, compressorId, compressorId, 0),
    PB_FIELD(  2, FLOAT   , OPTIONAL, STATIC  , OTHER, CompressorSettings, pidSetpoint, compressorId, 0),
    PB_FIELD(  3, FLOAT   , OPTIONAL, STATIC  , OTHER, CompressorSettings, pidP, pidSetpoint, 0),
    PB_FIELD(  4, FLOAT   , OPTIONAL, STATIC  , OTHER, CompressorSettings, pidI, pidP, 0),
    PB_FIELD(  5, FLOAT   , OPTIONAL, STATIC  , OTHER, CompressorSettings, pidD, pidI, 0),
    PB_FIELD(  6, FLOAT   , OPTIONAL, STATIC  , OTHER, CompressorSettings, requestedHotWaterTemp, pidD, 0),
    PB_FIELD(  7, FLOAT   , OPTIONAL, STATIC  , OTHER, CompressorSettings, heatingHysteresis, requestedHotWaterTemp, 0),
    PB_FIELD(  8, FLOAT   , OPTIONAL, STATIC  , OTHER, CompressorSettings, requestedCoolWaterTemp, heatingHysteresis, 0),
    PB_FIELD(  9, FLOAT   , OPTIONAL, STATIC  , OTHER, CompressorSettings, coolingHysteresis, requestedCoolWaterTemp, 0),
    PB_FIELD( 10, BYTES   , OPTIONAL, STATIC  , OTHER, CompressorSettings, pidSensorAddr, coolingHysteresis, 0),
    PB_FIELD( 11, BYTES   , OPTIONAL, STATIC  , OTHER, CompressorSettings, hotWaterSensorAddr, pidSensorAddr, 0),
    PB_FIELD( 12, BYTES   , OPTIONAL, STATIC  , OTHER, CompressorSettings, coolingStartSensorAddr, hotWaterSensorAddr, 0),
    PB_FIELD( 13, BYTES   , OPTIONAL, STATIC  , OTHER, CompressorSettings, coolingStopSensorAddr, coolingStartSensorAddr, 0),
    PB_LAST_FIELD
};

const pb_field_t TempInfo_fields[3] = {
    PB_FIELD(  1, BYTES   , OPTIONAL, STATIC  , FIRST, TempInfo, SensorAddr, SensorAddr, 0),
    PB_FIELD(  2, FLOAT   , OPTIONAL, STATIC  , OTHER, TempInfo, Temp, SensorAddr, 0),
    PB_LAST_FIELD
};

const pb_field_t PIDInfo_fields[10] = {
    PB_FIELD(  1, INT32   , OPTIONAL, STATIC  , FIRST, PIDInfo, compressorId, compressorId, 0),
    PB_FIELD(  2, FLOAT   , OPTIONAL, STATIC  , OTHER, PIDInfo, In, compressorId, 0),
    PB_FIELD(  3, FLOAT   , OPTIONAL, STATIC  , OTHER, PIDInfo, Out, In, 0),
    PB_FIELD(  4, FLOAT   , OPTIONAL, STATIC  , OTHER, PIDInfo, P, Out, 0),
    PB_FIELD(  5, FLOAT   , OPTIONAL, STATIC  , OTHER, PIDInfo, I, P, 0),
    PB_FIELD(  6, FLOAT   , OPTIONAL, STATIC  , OTHER, PIDInfo, D, I, 0),
    PB_FIELD(  7, FLOAT   , OPTIONAL, STATIC  , OTHER, PIDInfo, dispP, D, 0),
    PB_FIELD(  8, FLOAT   , OPTIONAL, STATIC  , OTHER, PIDInfo, dispI, dispP, 0),
    PB_FIELD(  9, FLOAT   , OPTIONAL, STATIC  , OTHER, PIDInfo, dispD, dispI, 0),
    PB_LAST_FIELD
};

const pb_field_t FlowInfo_fields[4] = {
    PB_FIELD(  1, INT32   , OPTIONAL, STATIC  , FIRST, FlowInfo, sensorId, sensorId, 0),
    PB_FIELD(  2, INT32   , OPTIONAL, STATIC  , OTHER, FlowInfo, LitersPerSecond, sensorId, 0),
    PB_FIELD(  3, INT32   , OPTIONAL, STATIC  , OTHER, FlowInfo, absoluteValue, LitersPerSecond, 0),
    PB_LAST_FIELD
};


